global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: bfsi-api
    metrics_path: /metrics
    static_configs:
      - targets: ["bfsi-agent-api:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: opentelemetry-collector
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: kafka
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerts/*.yml