apiVersion: 1

providers:
  - name: BFSI AI Platform
    orgId: 1
    folder: BFSI
    type: file
    disableDeletion: false
    updateIntervalSeconds: 30
    options:
      path: /var/lib/grafana/dashboards